<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_Webp
 */

use Unexpected\Webp\Block\Adminhtml\System\Config\ProgressBar;

/** @var ProgressBar $block */
?>

<div id="progressbar"
     data-mage-init='{
            "progressbar": {
                "div": "#progressbar",
                "label": ".progress-label"
            }
       }'>
    <div class="progress-label"></div>
</div>


