<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_Webp
 */

use Unexpected\Webp\Block\Adminhtml\System\Config\ProgressBar;

/** @var ProgressBar $block */
?>

<div id="progressBar" data-mage-init='{
        "progressbar": {
                "divProgressBar": "#progressbar",
                "divProgress": "#progress"
            }
        }'>
    <div id="progress">0%</div>
</div>

