<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_Webp
 */

use Unexpected\Webp\Block\Adminhtml\System\Config\ToggleSwitch;

/** @var ToggleSwitch $block */
?>

<div id="switcher" data-bind="scope: 'toggleSwitch-scope'">
    <label class="switch">
        <input type="hidden" name="groups[general][fields][enable][value]"
               data-bind="value: getValue()"/>
        <input type="checkbox" data-bind="checked: isChecked">
        <span data-bind="css: { sliderOne: isChecked, slider: !isChecked() }" class="round" id="spa"></span>
    </label>
    <span id="toggle" data-bind="text: text"></span>
</div>

<script type="text/x-magento-init">
{
  "#switcher": {
        "Magento_Ui/js/core/app": {
        "components": {
          "toggleSwitch-scope": {
            "component": "Unexpected_Webp/js/system/config/toggle-switch",
            "isChecked": <?= json_encode($block->getValue()) ?>
          }
        }
      }
  }
}
</script>
