<?php

use Unexpected\Webp\Block\Adminhtml\Conversion\Time;

/** @var Time $block */
$elementHtml = $block->getTimeElementHtml();
$elementName = $block->getTimeElementName();
$elementValue = $block->getTimeElementValue();
?>

<div class="admin__field-label">
    <label>
        <span>
            Time
        </span>
    </label>
</div>
<div class="admin__field-control">
    <?= $elementHtml ?>
</div>

<script>
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        $(function () {
            const formName = 'time';

            setInitValue();

            function setInitValue() {
                const value = '<?= $elementValue ?>';
                $('#time')
                    .attr('data-form-part', 'webp_form')
                    .prop('name', formName)
                    .val(value);

                const values = value.split(',');
                $(`select[data-ui-id="form-element-timehour"]`).val(values[0]);
                $(`select[data-ui-id="form-element-timeminute"]`).val(values[1]);
                $(`select[data-ui-id="form-element-timesecond"]`).val(values[2]);
            }

            $(`select[name="${formName}"]`).on('change', function () {
                let time = '';

                $(`select[name="${formName}"]`).each(function (i, el) {
                    const id = $(el).data('ui-id');
                    const value = $(el).val();

                    if (id === 'form-element-<?= $elementName ?>hour') {
                        time = value;
                    } else {
                        time += `,${value}`;
                    }
                });

                $('#time').val(time);
            });
        });
    });
</script>

