<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_Webp
 */

use Unexpected\Webp\Block\Adminhtml\Conversion\Tree;

/** @var Tree $block */
?>

<div class="webp-folders-side-col">
    <div class="tree-holder">
        <div id="folder-tree"></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Unexpected_Webp/js/conversion/treenode": {}
        }
    }
</script>
