<?php
/**
 * @author Unexpected Team
 * @copyright Copyright (c) 2020 Unexpected
 * @package Unexpected_Webp
 */

use Unexpected\Webp\Block\Adminhtml\Conversion\Tree;

/** @var Tree $block */
?>

<div class="categories-side-col">
    <div class="tree-holder">
        <div id="folder-tree"></div>
        <!--        <div id="tree-div" class="tree-wrapper"></div>-->
    </div>
</div>

<div data-id="information-dialog-tree" class="messages" style="display: none;">
    <div class="message message-notice">
        <div><?= $block->escapeHtml(__('This operation can take a long time')) ?></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Unexpected_Webp/js/conversion/treenode": {}
        }
    }
</script>
