<?php
/**
 * @author GreenRivers Team
 * @copyright Copyright (c) 2020 GreenRivers
 * @package GreenRivers_Webp
 */

use GreenRivers\Webp\Block\Adminhtml\Conversion\Tree;

/** @var Tree $block */
?>

<div class="webp-folders-side-col">
    <div class="tree-holder">
        <div id="folder-tree"></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "GreenRivers_Webp/js/conversion/treenode": {}
        }
    }
</script>
